CREATE TABLE TB_ORDEM_SERVICO
	(
	Id INT,
	Codigo INT,
	Nome Varchar(150),

	)

ALTER TABLE TB_ORDEM_SERVICO	ADD CONSTRAINT Id_Componente FOREIGN KEY (Id) REFERENCES TB_COMPONENTE (Id)
ALTER TABLE TB_ORDEM_SERVICO ADD CONSTRAINT Codigo_Componente FOREIGN KEY (Codigo) REFERENCES TB_COMPONENTE (Codigo)


drop table TB_COMPONENTE

CREATE TABLE TB_COMPONENTE
	(
	Id INT PRIMARY KEY,
	Codigo INT UNIQUE ,
	Indice Varchar(150),
	SKU INT UNIQUE,
	Descricao Varchar(500),
	Preco Decimal(10,2),
	Quantidade INT
	)